<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Almaci Uniformes</title>
<link href="<?php $this->asset('template.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('superfish.css','menu/css'); ?>" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php $this->asset('style.css','menu/css'); ?>" rel="stylesheet" type="text/css" />
<link id="textContentCss" href="<?php $this->asset('menu-text-01-Default.css','menu/css'); ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php $this->asset('jquery.fancybox.css','fancy/css'); ?>" media="screen" />
<link href="<?php $this->asset('form.css','css'); ?>" rel="stylesheet" type="text/css" />


   
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" src="<?php $this->asset('jquery.fancybox.js','fancy/js'); ?>"></script>
<script type="text/javascript" src="<?php $this->asset('control.js','fancy/js'); ?>"></script>

<script src="<?php $this->asset('superfish.js','menu/js'); ?>" type="text/javascript"></script>
<script src="<?php $this->asset('scriptsInit.js','menu/js'); ?>" type="text/javascript"></script>



        
        
<link href="<?php $this->asset('tabela.css','css'); ?>" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="header">
<div id="topo">
  <h1>Almaci Uniformes</h1>
</div>

<div id="menu">

  <?php echo $this->render('menu.phtml'); ?>     

  </div>
</div>
<div id="container">
  <div id="title">Produtos Cadastrados</div>
  <div id="vitrine">
<ul class="album">
      <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
       <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
       <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
       <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
      <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
       <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>
       <li>
        <div id="image-galeria"><a class="fancybox" href="../imagens/modelos/adm01.jpg" data-fancybox-group="gallery"><img src="../imagens/modelos/adm01.jpg" width="120" height="179" border="0" /></a></div>
        <div id="actions-galeria"><a href="edit-modelo.php"><img src="imagens/edit-icon.png" title="Editar modelo" width="20" height="20" border="0" /><img src="imagens/del.png" width="25" height="20" border="0" title="Excluir" /></a></div>
        <div id="legendas">Administrativo</div>
      </li>

      
    </ul>
  </div>
</div>
<div id="footer">Desenvolvido por Aplus Tecnologia - (31) 3245-5764</div>
</body>
</html>